config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'gallery#index'

	get 'presentation/slide1' => 'slides#slide1', :as => :slide1
	get 'presentation/slide2' => 'slides#slide2', :as => :slide2
	get 'presentation/slide3' => 'slides#slide3', :as => :slide3
	get 'presentation/slide4' => 'slides#slide4', :as => :slide4
	get 'presentation/slide5' => 'slides#slide5', :as => :slide5
	get 'presentation/slide6' => 'slides#slide6', :as => :slide6
	get 'presentation/slide7' => 'slides#slide7', :as => :slide7
	get 'presentation/slide8' => 'slides#slide8', :as => :slide8
	get 'presentation/slide9' => 'slides#slide9', :as => :slide9
	get 'presentation/slide10' => 'slides#slide10', :as => :slide10
	get 'presentation/slide11' => 'slides#slide11', :as => :slide11
	get 'presentation/slide12' => 'slides#slide12', :as => :slide12

	get 'galerija' => 'gallery#index', :as => :gallery
	get 'dodaj-sliku' => 'gallery#new',  :as => :new_picture
	post 'spremi-sliku' => 'gallery#create',  :as => :create_picture
	delete 'izbrisi-sliku/:picture_id' => 'gallery#destroy', :as => :destroy_picture
 

	get 'o-predmetu' => 'static#about', :as => :about

	#projects
	get 'projekti' => 'projects#index', :as => :projects
 	get 'dodaj-projekt' => 'projects#new', :as => :new_project
 	post 'stvori-projekt' => 'projects#create', :as => :create_project
 	delete 'izbrisi-projekt/:project_id' => 'projects#destroy', :as => :destroy_project
 
	# get 'obavijesti' => 'news#index', :as => :news
	# get 'nova-obavijest' => 'news#new', :as => :new_news
	# post 'stvori-obavijest' => 'news#create', :as => :create_news

end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
	before_action :authenticate_admin!, only: [:new, :create]

	layout 'gallery'

	def index
		@projects = Project.order('created_at DESC').all
	end

	def new
		
	end


	def create
		@project = Project.new(project_params)


		if @project.save
			flash[:notice] = 'Projekt je dodan'
			
		else
			flash[:notice] = 'Nije uspjelo dodavanje'
		end	
		redirect_to projects_path

	end

    def destroy
	    Project.find(params[:project_id]).destroy
	    flash[:notice] = "Project deleted"
	    redirect_to projects_path
	  end

    def project_params
    	params.require(:project).permit(:link, :name) 
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
 <!-- Page Content -->
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">Projekti</h1>
        <% if admin_signed_in? %>
        	<%= link_to 'DODAJ PROJEKT', new_project_path %>
        <% end %>
    </div>
    <div class="col-lg-12 thumb">
    	<%# link_to 'Mogucnosti HTML5 jezika', slide1_path, :class => 'project' %>
        <!-- <a class="project" href="projects.html">Mogucnosti HTML5 jezika</a> -->
    </div>
	<ul style="margin: 0 40px; list-style-type: none;">
		<% @projects.each do |project| %>
	    	<li>
                <a href="<%= project.link %>" style="display: inline-block; margin-right: 50px; "><%= project.name %></a>
                <% if admin_signed_in? %>
                    <%= link_to 'Izbrisi projekt', destroy_project_path(project.id), :method => 'delete' %>
                <% end %>
            </li>
		<% end %> 
	</ul>
	  

app/views/projects/new.html.erb
<div class="picture-form">

    <%= form_for(:project, url: create_project_path, :html => {:class => 'new-painting-form'}, :method => 'post') do |f| %>
        <div class="form__element">
            <%= f.text_field :name, :placeholder => 'Ime', :class => 'form__input  form-control', autofocus: true %> 
        </div>
         <div class="form__element">
            <%= f.text_field :link, :placeholder => 'Link', :class => 'form__input  form-control', autofocus: true %> 
        </div>
         <div class="form-group ">
          <div class="contact__submit">
            <%= f.submit 'DODAJ PROJEKT', :class => 'btn btn-primary' %>
          </div>
        </div>
  <% end %>


</div>