config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'gallery#index'

	get 'presentation/slide1' => 'slides#slide1', :as => :slide1
	get 'presentation/slide2' => 'slides#slide2', :as => :slide2
	get 'presentation/slide3' => 'slides#slide3', :as => :slide3
	get 'presentation/slide4' => 'slides#slide4', :as => :slide4
	get 'presentation/slide5' => 'slides#slide5', :as => :slide5
	get 'presentation/slide6' => 'slides#slide6', :as => :slide6
	get 'presentation/slide7' => 'slides#slide7', :as => :slide7
	get 'presentation/slide8' => 'slides#slide8', :as => :slide8
	get 'presentation/slide9' => 'slides#slide9', :as => :slide9
	get 'presentation/slide10' => 'slides#slide10', :as => :slide10
	get 'presentation/slide11' => 'slides#slide11', :as => :slide11
	get 'presentation/slide12' => 'slides#slide12', :as => :slide12

	get 'galerija' => 'gallery#index', :as => :gallery
	get 'dodaj-sliku' => 'gallery#new',  :as => :new_picture
	post 'spremi-sliku' => 'gallery#create',  :as => :create_picture
	delete 'izbrisi-sliku/:picture_id' => 'gallery#destroy', :as => :destroy_picture
 

	get 'o-predmetu' => 'static#about', :as => :about

	#projects
	get 'projekti' => 'projects#index', :as => :projects
 	get 'dodaj-projekt' => 'projects#new', :as => :new_project
 	post 'stvori-projekt' => 'projects#create', :as => :create_project
 	delete 'izbrisi-projekt/:project_id' => 'projects#destroy', :as => :destroy_project
 
	# get 'obavijesti' => 'news#index', :as => :news
	# get 'nova-obavijest' => 'news#new', :as => :new_news
	# post 'stvori-obavijest' => 'news#create', :as => :create_news

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :create]

	layout 'gallery'

	def index
		@pictures = Picture.order('created_at DESC').all
	end

	def new
		
	end


	def create
		@picture = Picture.new(picture_params)


		if @picture.save
			flash[:notice] = 'Slika je dodana.'
			redirect_to gallery_path
		else
			flash[:notice] = 'Dodavanje nije uspjelo.'
			render 'new'
		end	

	end

    def destroy
	    picture.find(params[:picture_id]).destroy
	    flash[:notice] = "Slika je izbrisana."
	    redirect_to gallery_path
	  end

    def picture_params
    	params.require(:picture).permit(:name, :pic) 
    end




end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/index.html.erb
   <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12" >
                <%# audio_tag("Beethoven.mp3", autoplay: true, controls: true) %>
                <!-- <audio controls loop style="right: 15px; position: absolute;">
                  <source src="audio/amclassical_beethoven_fur_elise.mp3" type="audio/mpeg">
                </audio> -->
            </div>
        </div>
        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Galerija</h1>
            </div>

            
            <% @pictures.each_with_index do |picture, i| %>
                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                    <a class="thumbnail" href="#" >
                        <%= image_tag picture.pic.url,:class => 'img-responsive', :data => {:range => i, :name => picture.name} %>
                    </a>
                    <% if admin_signed_in? %>
                        <%= link_to 'Izbrisi sliku', destroy_picture_path(picture.id), :method => 'delete' %>
                    <% end %>
                </div>
            <% end %>    

            <div id="myModal" class="modal">
                <span class="close">&times;</span>
                <img class="modal-content" id="img01">
               
                <div id="caption"></div>
                
                <a class="prev" onclick="slide(-1)">&#10094;</a>
                <a class="next" onclick="slide(1)">&#10095;</a>
            </div>

            <script>
                var modal = document.getElementById('myModal');
                var modalImg = document.getElementById("img01");
                var id = -1;
                $(".img-responsive").on("click", function(){
                    modal.style.display = "block";
                    modalImg.src = this.src;
                    // captionText.innerHTML = this.alt;
                    id = $(this).data("range");
                    pic_name = $(this).data("name");
                    $("#caption").html(pic_name);
                });
                var span = document.getElementsByClassName("close")[0];
                span.onclick = function() {
                    modal.style.display = "none";
                }
                function slide(x){
                    id = id + x;
                    len = $(".img-responsive").length;
                    if(id >= len){
                        id = 0;
                    } else if(id < 0){
                        id = len-1;
                    }
                    image = $(".img-responsive").filter('[data-range="'+id+'"]')[0];
                    modalImg.src = image.src;
                    pic_name = image.attributes[2].value;
                    $("#caption").html(pic_name);
                }
            </script>
        </div>

        <hr>

        <div id="footer-info">
            <div class="col-lg-12">
                <div class="footer-area">
                    <a class="footer-info-item last" style="left: 0; position: absolute;" href="https://www.math.pmf.unizg.hr/hr/multimedijski-sustavi-pravila">PMF Matematika</a>
                    <a class="footer-info-item last" style="right: 0; position: absolute;" href="https://www.facebook.com/groups/522346087960398/" target="_blank"><%= image_tag 'fejs.png', :width => '30px', :height => '30px' %></a>
                </div>
            </div>
        </div>

    </div>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>

app/views/gallery/new.html.erb
<style>
        
   

    </style>

    <script>
        


    </script>

<div class="picture-form">

    <%= form_for(:picture, url: create_picture_path, :html => {:class => 'new-painting-form'}, :method => 'post') do |f| %>
         <div class="form__element" data-action="show-preview">
            <label class="custom-file-upload form__input  form-control">
                ODABERI SLIKU
                <%= f.file_field :pic %>
            </label>  

        </div>
        <div id="target" class="image-preview">

        </div>
        <div class="form__element">
            <%= f.text_field :name, :placeholder => 'Name', :class => 'form__input  form-control', autofocus: true %> 
        </div>
         <div class="form-group ">
          <div class="contact__submit">
            <%= f.submit 'DODAJ SLIKU', :class => 'btn btn-primary' %>
          </div>
        </div>
  <% end %>


</div>